tasks-bot:
  db:
    scheme: postgresql # sqlite, etc
    engine: asyncpg
    host: host
    port: 1234

    echo: false
    echo_pool: false
    pool_size: 50
    max_overflow: 10

  rabbit:
    host: host
    port: 1234
    vhostname: virtual_host_name
    secure: true

  bot:
    owner_tg_id: 87396076

  run:
    host: 0.0.0.0
    port: 8080

    webhook:
      host: https://example.com
      path: /any/webhook
