name: Python checks üêç

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/**"
      - "bot-app/**"

jobs:
  python-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install "black==25.1.0"

#      - name: Black
#        run: black --check --diff ./

      - name: Install poetry
        run: |
          pip install "poetry==2.1.1"

      - name: Install dependencies
        run: poetry sync --no-root --no-interaction --no-ansi

      - name: Run mypy
        run: poetry run mypy ./

      # –°–æ–∑–¥–∞—é .env —Ñ–∞–π–ª –∏–∑ —à–∞–±–ª–æ–Ω–∞ –¥–ª—è —Ç–µ—Å—Ç–æ–≤
      - name: Setup .env file
        run: cp bot-app/.env.template bot-app/.env

      # –ó–∞–ø—É—Å–∫–∞—é —Ç–µ—Å—Ç—ã
      - name: Run tests
        run: poetry run pytest -s