name: Test Workflow dependency
on:
  workflow_run:
    workflows: ["Python checks üêç"]
    types:
      - completed

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow
        run: echo "Head branch ‚Äî ${{ github.event.workflow_run.head_branch }}"

      - name: Say hello
        run: echo "Hello World!"